Repository al-mabsut/muslimah, pull requests merged in 2024-03, with the labels that each got.

#439 combine all dependabot prs 2024 03 01 4682
  package-lock.json
Labels: dependencies, automerge

#440 Introduce basic terminology modal
  src/components/Content/index.js
  src/components/Hanafiyyah/en/Hayd/index.stories.js
  src/components/Hanafiyyah/en/Indeterminate/index.stories.js
  src/components/Hanafiyyah/en/Istihadah/index.stories.js
  src/components/Hanafiyyah/en/MostLikelyHayd/index.stories.js
  src/components/Hanafiyyah/en/MostLikelyIstihadah/index.stories.js
  src/components/Hanafiyyah/en/MostLikelyTuhr/index.stories.js
  src/components/Hanafiyyah/en/OngoingHayd/index.stories.js
  src/components/Hanafiyyah/en/Tuhr/index.stories.js
  src/components/Hidayah/index.js
Labels: bug, enhancement, automerge

#441 Introduce basic level terminologies
  contents/hanafi/en/4_ruling_bleeding_most_likely_hayd.md
  contents/hanafi/en/5_ruling_of_ongoing_hayd_till_habit.md
  contents/hanafi/en/6_ruling_of_ongoing_hayd_till_10_days.md
  src/components/Content/index.js
  src/components/Content/terminologies.json
  src/components/Hidayah/index.js
Labels: enhancement, automerge

#443 Bump version 0.1.2
  package-lock.json
  package.json
Labels: automerge

#448 combine all dependabot prs 2024 03 04 3723
  package-lock.json
Labels: dependencies, automerge

#455 combine all dependabot prs 2024 03 06 9101
  package-lock.json
Labels: dependencies, automerge

#458 combine all dependabot prs 2024 03 06 10507
  package-lock.json
Labels: dependencies, automerge

#468 combine all dependabot prs 2024 03 08 1449
  package-lock.json
Labels: dependencies, automerge

#472 Adjust fiqh rulings
  contents/hanafi/en/13_ruling_istihadah.md
  contents/hanafi/en/4_ruling_bleeding_most_likely_hayd.md
  contents/hanafi/en/5_ruling_of_ongoing_hayd_till_habit.md
  contents/hanafi/en/8_ruling_bleeding_most_likely_istihadah.md
  src/components/Content/terminologies.json
Labels: documentation

#473 combine all dependabot prs 2024 03 09 9657
  package-lock.json
Labels: dependencies, automerge

#488 combine all dependabot prs 2024 03 11 9182
  package-lock.json
Labels: dependencies, automerge

#504 combine all dependabot prs 2024 03 13 8634
  package-lock.json
  package.json
Labels: dependencies, automerge

#511 Downgrade storybook/preact-vite
  package-lock.json
  package.json
Labels: dependencies, automerge

#512 Allow links to be clickable
  contents/hanafi/en/8_ruling_bleeding_most_likely_istihadah.md
  src/components/Content/index.js
Labels: enhancement, automerge

#525 combine all dependabot prs 2024 03 16 7912
  package-lock.json
  package.json
Labels: automerge

#533 combine all dependabot prs 2024 03 19 3274
  package-lock.json
Labels: dependencies, automerge

#536 combine all dependabot prs 2024 03 19 2924
  package-lock.json
Labels: dependencies, automerge

#596 combine all dependabot prs 2024 03 19 6071
  package-lock.json
Labels: dependencies, automerge

#624 combine all dependabot prs 2024 03 20 8169
  package-lock.json
Labels: dependencies, automerge

#626 combine all dependabot prs 2024 03 20 1645
  package-lock.json
Labels: dependencies, automerge

#627 Downgrade storybook/preact-vite
  package-lock.json
  package.json
Labels: dependencies, automerge

#657 Downgrade storybook/preact-vite
  package-lock.json
  package.json
Labels: dependencies, automerge

#664 combine all dependabot prs 2024 03 25 9385
  package-lock.json
Labels: dependencies, automerge

#685 Revert "Dependabot: Bump @storybook/preact-vite from 7.6.17 to 8.0.5"
  package-lock.json
  package.json
Labels: dependencies, automerge

#687 combine all dependabot prs 2024 03 29 5730
  package-lock.json
Labels: dependencies, automerge
